### ISSUE TITLE
Dependency property

### ISSUE THREAD

**Issue by pumba-lt** [ewilderj/doap#28] opened 2016-08-08 13:59 UTC
DOAP does not seem to include any properties to describe relationships (dependencies) between projects and/or their releases.

**Comment by sshikov** [comment] 2017-01-23 07:27
I think, dependencies support should be at least as capable as in maven pom.xml - just implemented in RDF way.

**Comment by ewilderj** [comment] 2017-08-09 17:12
Yes, I left dependencies out in the first case of writing DOAP, because I wanted to solve the simpler problem first. Dependencies somewhat relies on the underlying packaging system, so I'm not yet sure what the best way of integrating them actually is. 

It would be good if @pumba-lt and @sshikov you could describe some of your expected use cases.

**Comment by ewilderj** [comment] 2017-08-09 17:53
OK, so getting myself back up to speed this is actually discussed in Issue #1 

TL;DR you can use http://ontologi.es/doap-deps# until such time as we merge dependency handling into DOAP.

Closing because further discussion should happen in #1

**Comment by ewilderj** [comment] 2017-08-09 17:54
Duplicate of #1

**Closed by ewilderj** 2017-08-09 17:54 UTC
Labels: feature-discussion

**Comment by pumba-lt** [comment] 2017-08-10 20:21
My use case was scraping Maven central repository to transform artifact metadata and their dependencies to RDF. I gave up because there was too much data.
